### ISSUE TITLE
Errors in your paper

### ISSUE THREAD

**Issue by hn18001** [magic-research/PLLaVA#10]
Are there some errors in your paper? In Table3: Results on MVBench, the best performance of AA, OE, OI, MD, MC, MA are ST-LLM，but they are not bolded.
![image](https://github.com/magic-research/PLLaVA/assets/15153971/f65cb937-c651-4fac-9200-c57d99168018)

**Comment by zhoudaquan** [comment]
> Are there some errors in your paper? In Table3: Results on MVBench, the best performance of AA, OE, OI, MD, MC, MA are ST-LLM，but they are not bolded. ![image](https://private-user-images.githubusercontent.com/15153971/326648270-f65cb937-c651-4fac-9200-c57d99168018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDUyMzEsIm5iZiI6MTcxNDQ0NDkzMSwicGF0aCI6Ii8xNTE1Mzk3MS8zMjY2NDgyNzAtZjY1Y2I5MzctYzY1MS00ZmFjLTkyMDAtYzU3ZDk5MTY4MDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAyNDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMGNiZDU1MTdmNjU5YmU1ZDY3MDlkNDhkNGRhMmI0N2QyOTBkZmZlZmYwNGIyMzU2MWVmNzM5NGIxMWU0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jw_U15ZdEwgGTOH56XLUqxWTW9OMYTXR6JWCHu4iYHE)

Hi,

Thanks for pointing out the typos in the table. We will correct the highlights.

Regards,
DQ
