### ISSUE TITLE
Raw image data

### ISSUE THREAD

**Issue by xumingze0308** [magic-research/PLLaVA#11]
Should we download raw image data from [M3IT](https://huggingface.co/datasets/MMInstruction/M3IT)? I don't understand how to get the image name from M3IT to the image names in the json files you provided. Thank you!

**Comment by cathyxl** [comment]
Hi @xumingze0308 , we didn't use the image data from M3IT. If you want to reproduce our model, you have no need to do it.

**Comment by xumingze0308** [comment]
Thanks for this quick reply. But in this [file](https://github.com/magic-research/PLLaVA/blob/94bcf9ff7c3cded74f9018d08f316ebc6b256ab5/tasks/train/instruction_data.py#L10), you are using a list of image datasets, where should we download these raw images, from the original data source? Thanks!

**Comment by pllava** [comment]
Sorry for the confusion. 

Some of the configuration would be overwritten at run time [here](https://github.com/magic-research/PLLaVA/blob/94bcf9ff7c3cded74f9018d08f316ebc6b256ab5/scripts/train_pllava_13b.sh#L25)

We set the train corpus to videochat2_video for training pllava.

**Comment by xumingze0308** [comment]
Oh, I got it. Thanks for this kind answering!
