### ISSUE TITLE
finetuning PLLaVA - IMAGEs for Video Analysis 

### ISSUE THREAD

**Issue by sureshtmca** [magic-research/PLLaVA#28]
My Objective is 'video analysis' of a specific subject. I have images pertaining to that subject not videos. Question ) 
Can I use images to finetune the 'PLLaVa_7b as the pretrained model' ? If so, can the training dataset format be used as below :
{"row_idx":0,"row":{"image":{"src":".. / IMG1.jpg","height":4032,"width":3024},"caption":"xyxxxyxxx"},"truncated_cells":[]}

**Comment by ermu2001** [comment]
Interesting perspective.

Most simple way here is to preprocess the images and convert them to gif files, then run the training untouched. 

If I get you right, this should reveal the model's understanding of static video of objects?

**Comment by sureshtmca** [comment]
"If I get you right, this should reveal the model's understanding of static
video of objects?

" the images and convert them to gif files, then run the training
untouched" -

Any sources you can recommend to quickly jump start and do the said
preprocessing please?

Thanks

**Comment by sureshtmca** [comment]
Thank you ...
On your suggestion, if i have multiple sequence of images that reflects the activity of a subject, IMG to GIF conversion makes sense with the movement in the GIF file. But my image is a stand alone static visual, post conversion also it is same stand alone and static without any movement. So does this aspect work for PLLaVA. Believe me if I can do this, this is going to create a domain specific beautiful LVLM.

**Comment by sureshtmca** [comment]
as i can't wait for the response, i found a way to deal this issue. Let me try that way of training

**Comment by Namzakku** [comment]
Hi @sureshtmca 
Would you mind sharing your solution to this problem? Many thanks!

**Comment by sterzhang** [comment]
> as i can't wait for the response, i found a way to deal this issue. Let me try that way of training

Hi, may I ask how it is going now?
