### ISSUE TITLE
Training time consumption

### ISSUE THREAD

**Issue by hmxiong** [magic-research/PLLaVA#51]
Awesome, this work is existing and meaningful!!
Could you please tell me how much time and GPU it takes to train the entire model under the current settings? I like this job very much, but I may not have enough resources to implement it.

**Comment by ermu2001** [comment]
https://github.com/magic-research/PLLaVA/issues/1#issuecomment-2082587647

The largest model costs around 48 A100 GPU days.

The smaller models costs less.
cc @cathyxl

**Comment by Nastu-Ho** [comment]
How long does it take to train the 7B model?
