### ISSUE TITLE
figure name in paper

### ISSUE THREAD

**Issue by maylilyo** [magic-research/PLLaVA#7]
In Figure 10, you've named (a) Badminton match and (b) Street Saxophone, but I think they need to change their order

<img width="647" alt="image" src="https://github.com/magic-research/PLLaVA/assets/31491678/ff6935fc-d24f-4b1c-a1b2-01439c386c7a">

**Comment by cathyxl** [comment]
@maylilyo 😂thank you so much for pointing that out, we will change accordingly.
