### ISSUE TITLE
Eval Results.

### ISSUE THREAD

**Issue by liguopeng0923** [magic-research/PLLaVA#73]
Hi,

I reproduced successfully your results on qabench and mvbench. But the results are not normal on vcgbench with pllava-7b.
<img width="360" alt="image" src="https://github.com/magic-research/PLLaVA/assets/61257834/99f27709-9ce6-4201-87ab-4705806bc2f4">

**Comment by liguopeng0923** [comment]
I solve it by changing the different chatgpt API.

**Comment by hulianyuyy** [comment]
When i test the model on the MVBench benchmark, i encounter the error "error decoding DATAS/MVBench/video/ssv2_video/166583.webm". Have you encoutered the same error and knowd how to solve it? Thanks!

**Comment by Li-Jinsong** [comment]
> When i test the model on the MVBench benchmark, i encounter the error "error decoding DATAS/MVBench/video/ssv2_video/166583.webm". Have you encoutered the same error and knowd how to solve it? Thanks!

Did u solve it? i encounter the same error.😭

**Comment by hulianyuyy** [comment]
> > When i test the model on the MVBench benchmark, i encounter the error "error decoding DATAS/MVBench/video/ssv2_video/166583.webm". Have you encoutered the same error and knowd how to solve it? Thanks!
> 
> Did u solve it? i encounter the same error.😭

You may set num_threads=1 in the VideoReader.

**Comment by Li-Jinsong** [comment]
> > > When i test the model on the MVBench benchmark, i encounter the error "error decoding DATAS/MVBench/video/ssv2_video/166583.webm". Have you encoutered the same error and knowd how to solve it? Thanks!
> > 
> > 
> > Did u solve it? i encounter the same error.😭
> 
> You may set num_threads=1 1 in the VideoReader.

This works for me, thx so much!

**Comment by Lexarymade** [comment]
i still facing error decoding DATAS/MVBench/video/ssv2_video/140639.webm problem after setting num_threads=1 1😭
