### ISSUE TITLE
Can you give some instructions on fine-tuning?

### ISSUE THREAD

**Issue by YepJin** [magic-research/PLLaVA#9]
Many thanks!

**Comment by ermu2001** [comment]
Do you want to start training from the obtained pllava, or you mean video finetuning starting from a image LLM?

**Comment by YepJin** [comment]
okay, thanks. I will check it. Actually, I am thinking of whether there are some checkpoints so that I can fine-tune with my own datasets, rather than retrain the whole model.

**Comment by YepJin** [comment]
BTW, I guess there is no audio encoder in this model? Do you take audio information as input?

**Comment by cathyxl** [comment]
Hi, @YepJin,  you can continue fine-tuning by setting our models as pre-trained models. These models can be found in huggingface as listed in README.md.  We also provide an arg to assign pretrained path for training, please refer to https://github.com/magic-research/PLLaVA/blob/94bcf9ff7c3cded74f9018d08f316ebc6b256ab5/tasks/train/config_pllava_nframe.py#L41

 Additionally, we didn't incorporate audio input in our models.

**Comment by YepJin** [comment]
Great, thanks!
